FROM node:12

COPY package.json /opt/

WORKDIR /opt/

RUN npm install

COPY . /opt/app
WORKDIR /opt/app

ENTRYPOINT [""]
CMD ["npm", "run", "start-dev"]

HEALTHCHECK --interval=10s --timeout=10s --start-period=30s --retries=3 CMD curl -f http://localhost:$SERVICE_PORT/health